//this file contains the constant with the actions type
const SET_ROUTE = "SET_ROUTE"
const SET_MENU_HEIGHT = "SET_MENU_HEIGHT"
const SET_VIEW_HEIGHT = "SET_VIEW_HEIGHT"
const ADD_MESSAGE = "ADD_MESSAGE"
const SET_LANGUAGE = "SET_LANGUAGE"
const SET_USERNAME = "SET_USERNAME"
const INCREMENT_MESSAGE_COUNT = "INCREMENT_MESSAGE_COUNT"
const SET_THEME = "SET_THEME"
const RESET_DEFAULT_SETTINGS = "RESET_DEFAULT_SETTINGS"
const SEND_CTRL_AND_ENTER = "SEND_CTRL_AND_ENTER"
const SET_CLOCK_FORMAT = "SET_CLOCK_FORMAT"
const SET_LAST_SENDER = "SET_LAST_SENDER"
const ADD_USER_NOTIFICATION = "ADD_USER_NOTIFICATION"
const SET_INTERFACE_LANGUAGE = "SET_INTERFACE_LANGUAGE"
const SET_LOADING = "SET_LOADING"

export {
    SET_ROUTE,
    SET_MENU_HEIGHT,
    SET_VIEW_HEIGHT,
    ADD_MESSAGE,
    SET_LANGUAGE,
    SET_USERNAME,
    INCREMENT_MESSAGE_COUNT,
    SET_THEME,
    RESET_DEFAULT_SETTINGS,
    SEND_CTRL_AND_ENTER,
    SET_CLOCK_FORMAT,
    SET_LAST_SENDER,
    ADD_USER_NOTIFICATION,
    SET_INTERFACE_LANGUAGE,
    SET_LOADING
}