const SET_ROUTE = "SET_ROUTE"
const SET_MENU_HEIGHT = "SET_MENU_HEIGHT"
const SET_VIEW_HEIGHT = "SET_VIEW_HEIGHT"
const ADD_MESSAGE = "ADD_MESSAGE"
const SET_LANGUAGE = "SET_LANGUAGE"
const SET_USERNAME= "SET_USERNAME"
const INCREMENT_MESSAGE_COUNT = "INCREMENT_MESSAGE_COUNT"
const SET_THEME = "SET_THEME"
const RESET_DEFAULT_SETTINGS="RESET_DEFAULT_SETTINGS"

export {
    SET_ROUTE,
    SET_MENU_HEIGHT,
    SET_VIEW_HEIGHT,
    ADD_MESSAGE,
    SET_LANGUAGE,
    SET_USERNAME,
    INCREMENT_MESSAGE_COUNT,
    SET_THEME,
    RESET_DEFAULT_SETTINGS
}